### ISSUE TITLE
extension is not in the VScode Marketplace

### ISSUE THREAD

**Issue by didierva** [Microsoft/DevSkim-VSCode-Plugin#2]
trying to install it with ext install vscode-devskim and there is no extension of that name in the marketplace

**Comment by joshbw** [comment]
I screwed something up - I'll be republishing today.  Look for it there in the next couple of days.  Sorry for the delay

**Comment by joshbw** [comment]
https://marketplace.visualstudio.com/items?itemName=MS-DevSkim.vscode-devskim

**Comment by joshbw** [comment]
I've downloaded the plugin from the extension gallery and it looks like everything is good to go
