### ISSUE TITLE
DevSkim should have a "max file size" argument

### ISSUE THREAD

**Issue by scovetta** [Microsoft/DevSkim-VSCode-Plugin#41]
When running the DevSkim CLI against large files (10 MB+), progress is extremely slow. Since it's a bit less likely that these large files will contain interesting results, I think we should cap file sizes to analyze around maybe 100k or so, with the ability for the user to change if they want.

**Comment by joshbw** [comment]
That's an easy add - I'll get it done today and throw it in https://github.com/microsoft/DevSkim-VSCode-Plugin/pull/40.  I swear I had added that before, but maybe I never merged it?  I'll put it in settings (also, should have the settings file on the command line done today), with the default 100k

**Comment by joshbw** [comment]
merged into master
