### ISSUE TITLE
DevSkim commands not found

### ISSUE THREAD

**Issue by mojave27** [Microsoft/DevSkim-VSCode-Plugin#44]
Running DevSkim commands in vscode via Cmd+Shift+P, results in an error message:

`command 'devskim.scanWorkspace' not found`

This occurs in any workspace, **except** the workspace which was open when I originally installed the DevSkim extension.  In the workspace which was open when I originally installed the DevSkim extension, the commands work correctly.

![Screen Shot 2019-10-09 at 11 29 09 AM](https://user-images.githubusercontent.com/9810186/66509581-352b6900-ea88-11e9-95cd-2b8b0b808601.png)

![Screen Shot 2019-10-09 at 11 29 19 AM](https://user-images.githubusercontent.com/9810186/66509588-3b214a00-ea88-11e9-8324-528d427ed793.png)

Here are my vscode User settings:
```json
{
    "workbench.colorTheme": "Material Theme Darker High Contrast",
    "workbench.iconTheme": "eq-material-theme-icons-darker",
    "terminal.integrated.rightClickBehavior": "copyPaste",
    "editor.minimap.enabled": false,
    "terminal.integrated.fontWeight": "600",
    "breadcrumbs.enabled": true,
    "window.zoomLevel": 0,
    "eslint.provideLintTask": true,
    "eslint.alwaysShowStatus": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact"
    ],
    "editor.tokenColorCustomizations": {
        "comments": "#a8a790"
    },
    "java.configuration.checkProjectSettingsExclusions": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.panel.defaultLocation": "right",
    "workbench.startupEditor": "newUntitledFile",
    "extensions.autoUpdate": false,
    "explorer.confirmDragAndDrop": false,
    "devskim.enableBestPracticeRules": true,
    "devskim.enableManualReviewRules": true,
    "devskim.manualReviewerName": "mojave"
}
```

**Comment by mojave27** [comment]
I updated a setting (`"devskim.ignoreFilesList": ["*.json"]`) and was then able to run the devskim commands.

**Comment by joshbw** [comment]
Thanks - we are getting a new version ready to push in the next couple of weeks.  Looks like an exception was being thrown in the old code base, but in the current one I don't see it.

**Comment by gfs** [comment]
@joshbw is this closed out now?

**Comment by joshbw** [comment]
It is working in the current master, but hasn't been updated in the marketplace (it unfortunately has some hinkiness from the way VS Code works in which *all* extensions do there thing when the files are analyzed, not just DevSkim, and I wish I could negate though but its outside of the control of an extension)
