### ISSUE TITLE
GitHub Actions: Produce .vsix

### ISSUE THREAD

**Issue by joshbw** [Microsoft/DevSkim-VSCode-Plugin#46]
As we port our pipeline to GitHub actions, we should have it do the .vsix production

**Comment by mosslilley** [comment]
Hey! 
Not sure where the best place to ask is but how are you producing the `.visx` package currently? I might have missed something in the documentation. Running `vsce package` in the main directory works but it's putting the whole repo in the `.visix` file.

**Comment by gfs** [comment]
We need to use Azure DevOps for signing builds.
