### ISSUE TITLE
DevSkim conditions finding-region() is broken

### ISSUE THREAD

**Issue by mosslilley** [Microsoft/DevSkim-VSCode-Plugin#55]
## What

When a finding-region is specified for a condition the plugin doesn't search the region

## Why 

When a finding-region is matched with regex the values are strings. On the line below a string is added to an integer resulting in a string. 

https://github.com/microsoft/DevSkim-VSCode-Plugin/blob/8bbe7dd942ed00bdc2c3fd1741df3c6992c5eb5d/server/src/devskimWorker.ts#L519

## Example 

`finding-region(-5,5)` and the rule match is on line `16`

```
findingRange.start.line + regionMatch[1]
16 + "-5" === "16-5"
```

So `"16-5"` is passed into `GetDocumentPosition()`

https://github.com/microsoft/DevSkim-VSCode-Plugin/blob/8bbe7dd942ed00bdc2c3fd1741df3c6992c5eb5d/server/src/utility_classes/document.ts#L70

`"16-5"++` is NaN which causes problems with the rest of the function

Similar behavior for `endPos`

```
findingRange.end.line + regionMatch[2] + 1
16 + "5" + 1 === "1651"
```

While the NaN bug doesn't occur the line number is inaccurate

## How to fix

Use unary operators to cast the finding-range values to integers

**Comment by gfs** [comment]
Hey Moss,

Good catch.  Thanks for the detailed report.

Will fix.

**Comment by mosslilley** [comment]
Cheers! I'm about to put a PR in for you
