### ISSUE TITLE
Matched rules with conditions highlight the wrong text

### ISSUE THREAD

**Issue by mosslilley** [Microsoft/DevSkim-VSCode-Plugin#56]
## What 

Matched rules with conditions highlight the wrong text

## Why

When `DevSkimWorker.MatchesConditionPattern()` returns `true` `MatchesConditions()` returns `false` 

https://github.com/microsoft/DevSkim-VSCode-Plugin/blob/8bbe7dd942ed00bdc2c3fd1741df3c6992c5eb5d/server/src/devskimWorker.ts#L456

This causes the problem to be pushed as suppressed finding

## How to fix

Invert the logic so the function is returning false when there are no matches

`if(!DevSkimWorker.MatchesConditionPattern(condition, documentContents, findingRange, langID))`

**Comment by gfs** [comment]
Thanks for the detailed report.

Will fix.
