### ISSUE TITLE
Xaml files false http warning

### ISSUE THREAD

**Issue by AceSyntax** [Microsoft/DevSkim-VSCode-Plugin#7]
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"

I'm getting a warning in the form of a wavy purple line under the http text and an DS137138 error message in the output window in xaml files.   
Show potential Fixes, has a 'surpress permanently' but it does nothing.
I don't see any obvious way to turn this off.   I've read the guidance on this, but simply ignoring it is not acceptable.   Also it only works for file that are open in the VS editor, closed files are ignored.   
I personally wouldn't use this tool if I can't manage/get rid of these messages, but I do like the concept of this tool so I'm hoping you can fix this up for the v1.

**Comment by scovetta** [comment]
Thanks for the feedback -- we're working on this is two areas:

- You'll be able to global-ignore certain file globs.
- We'll have more complex filtering rules -- essentially, "match http://, but not if the line also contains xmlns". Both of these should address this, and we'll get these out as soon as we can.

Thanks for the feedback!

Related to https://github.com/Microsoft/DevSkim/issues/14

**Comment by joshbw** [comment]
The global ignore was just committed - shouldn't be hard to add *.XAML to the ruleset, though as I note in https://github.com/Microsoft/DevSkim/issues/14 we should probably also allow explicit file exclusions WITHIN the rules when we know the rule isn't a good fit for a specific file (or file type)

**Comment by joshbw** [comment]
This will be fixed in the release going out soon (hopefully this week)

**Comment by joshbw** [comment]
Fixed in 0.2.0: https://marketplace.visualstudio.com/items?itemName=MS-DevSkim.vscode-devskim
