### ISSUE TITLE
Switch to full word match

### ISSUE THREAD

**Issue by MarioSchwalbe** [Microsoft/DevSkim-VSCode-Plugin#9]
Hi,

in some piece of code using LLVM libs:
```c++
if (const auto constExpr = dyn_cast<ConstantExpr>(value)) {
    if (constExpr->getOpcode() == Instruction::BitCast)
        return getAlignment(constExpr->getOperand(0));
        // This is not a rand() call:        ^~~~
}
```

I get the `rand` part of the `getOperand()` call to be highlighted telling me:
```
[Devskim: Finding DS148264]
Do not use weak/non-cryptographic random number generators
Severity: [Important]
```

Apparently, this is not a `rand()` call at all. I guess the engine is doing a substring match only, not a full word match...

ciao,
Mario

**Comment by joshbw** [comment]
Oops, good catch, absolutely should have a \b to make the match more accurate

**Comment by joshbw** [comment]
Should be fixed in https://marketplace.visualstudio.com/items?itemName=MS-DevSkim.vscode-devskim

Thanks for pointing out the mistake
